#!/bin/sh -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

# We use install, not verify, because maven-invoker-tests need modules in this
# project  installed into the local repository before tests run.
./mvnw -T1C install -nsu "$@"
